### ISSUE TITLE
Touch controls in iPhone

### ISSUE THREAD

**Issue by gooddosh** [vc64web/virtualc64web#207] opened 2023-08-25 02:28 UTC
Greetings C64 Gods,

I took Jumpman, Choplifter and a few other games for a spin on my phone today. Yes, a joystick is probably just what the good doctor would order; but truth be told, I won't have one on me most of the time. So I've come to you with hat in hand to make a request for options for touch controls.

My first problem is that I can't use touch controls unless I start from somewhere on the C64 monitor area, obscuring my view of what's happening there. I can drag my left thumb off into the border; but if I release it, I have to start the process over. It isn't intuitive, and I die many unnatural deaths as a result. What I propose is an option to permanently lock the touch controls at the place of my choosing and have them be transparent, much like Action Buttons. This way, my thumbs or fingers would always know where to go (the joystick center would never move, only the virtual stick from that locked point). I wish to put the joystick and fire button in the margins. I'm trying to play in landscape view with the C64 border removed. I'd like the controls to be as close to the edges as possible, while still having enough room to move. This might help left-handed people too, if they can anchor controls opposite of mine.

Another request for the virtual touch joystick is an option to control its responsiveness. In my iPhone 10, it's drastically faster to me than how I relate to an actual joystick. So some option to control momentum of dragging the stick would be a huge help.

Regardless of the above, I'm in complete awe that a C64 is finally running on my iPhone. I can scarcely believe it when these old classic games pop up on the screen. I just love it. So thank you again.

**Comment by mithrendal** [comment] 2023-08-25 15:39
>My first problem is that I can't use touch controls unless I start from somewhere on the C64 monitor area, obscuring my view of what's happening there. I can drag my left thumb off into the border; but if I release it, I have to start the process over. It isn't intuitive, and I die many unnatural deaths as a result. 

confirmed. good find. 😀

It seems to work well in vc64webs bigger 32Bit brother https://vamigaweb.github.io so I probably fixed that there already without fixing it in the 8Bit guy ...

**Comment by mithrendal** [comment] 2023-08-25 21:16
first problem fixed. Touch control input in the blank screen i.e. outside of the c64 monitor screen should work now.  

pushed to https://vc64web.github.io  

`hint:` trigger the update of vc64web by hitting a button in the settings or wait until the second cold start when it will eventually update automatically

**Comment by gooddosh** [comment] 2023-08-26 00:57
Heck, I might get into Amiga soon. I couldn't afford it back then. No one makes games as interesting as these anymore. Too much money involved. It's like Hollywood. No imagination anymore. Everything is the same game with a new skin. I prefer to live in the past, at least in this regard. :)

**Comment by gooddosh** [comment] 2023-08-26 04:24
OK, I've updated. Starting from the margins has made the games much more playable but still frustrating, because I can't lock the positions of the controls. My natural tendency is to want to drag too far, so the base starts moving all over the place, and I get stressed out just from that while playing. I really need a way to lock them down.

**Comment by mithrendal** [comment] 2023-08-27 05:45
create an action button e.g. `stationary joystick patch` to patch the virtual touch joystick

as a language choose `javascript` instead of `actionscript`

```javascript
VirtualJoystick.prototype._onMove = function(x, y)
{
	if( this._pressed === true ){
		this._stickX	= x;
		this._stickY	= y;

		if(this._limitStickTravel === true){
			var deltaX	= this.deltaX();
			var deltaY	= this.deltaY();
			var stickDistance = Math.sqrt( (deltaX * deltaX) + (deltaY * deltaY) );
			if(stickDistance > this._stickRadius){
				var stickNormalizedX = deltaX / stickDistance;
				var stickNormalizedY = deltaY / stickDistance;
			
				this._stickX = stickNormalizedX * this._stickRadius + this._baseX;
				this._stickY = stickNormalizedY * this._stickRadius + this._baseY;
			} 		
		}
                this._move(this._stickEl.style, (this._stickX - this._stickEl.width /2), (this._stickY - this._stickEl.height/2));	
	}	
};
```


go to the snapshot browser in the menu and choose csdb.dk and start the test program anykeys
<img width="1166" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/91e39860-cc47-41ee-add3-a5375ec3a689">
 

here you can test and observe the behaviour of the floating touch joystick without dying a single life in a game.

<img width="1166" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/75f93177-85e4-4c59-bc66-e4c81fa50a96">

now press the action button which patches the stationary code and observe the behaviour of the stationary joystick.

I still think the `floating` mechanic is superior to the `stationary`. Maybe you are not yet used to it and you hold the device wrong (  https://www.wired.com/2010/06/iphone-4-holding-it-wrong/ ) ?

>Another request for the virtual touch joystick is an option to control its responsiveness. In my iPhone 10, it's drastically faster to me than how I relate to an actual joystick. So some option to control momentum of dragging the stick would be a huge help.

there is no dragging momentum. it is binary i.e. it maps to a digital joystick ... the best would be to train with the above anykeys program first where you can observe that the way or distance that you drag does not corresponds to a game sprites distance. it corresponds only to the direction.  

This remembers me very much to the time in the 80ties ... friends from school came to visit and for first time played pitstop II ... they literally destroyed my quickshot2 controller 

<img width="268" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/a8e089e8-d34f-44fd-ad99-5469567d108b">

because their brain thought that the harder they press it to the left the harder the car would steer to the inner curve of the road. 

But there is no momentum for the digital joystick ports. it only closes a digital circuit when pressing the joystick to the left. This is corresponds also to the drag distance as well. Even a very single swipe distance to the left and the circuit will already close and the c64 will detect the direction.

**Comment by mithrendal** [comment] 2023-08-27 11:21
<img width="894" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/2c8f7c23-893e-4125-a76f-f641deb4167e">

@gooddosh  forget about the above mentioned `patch script`, I just added the switch `fixed base position of touch joystick` for that in the settings. 😎

🤔Maybe I am wrong in moving the base of the virtual touch joystick? Because it might lead some users to think that this particular movement of the visualisation of the touch control corresponds to the movement of the hero they are controlling inside the c64 game. Which is not the case. Its only all about directions with c64 joysticks.

What is the advantage of moving the base then ? shorter reaction time when moving into the opposite direction. When not let the base follow the fingers in the direction of the swipe, the finger would have to travel all the way back to trigger the opposite direction. 

What is the advantage of the fixed base then ? It kinda disciplines you to always move your fingers back to the base in order to move in the opposite direction.

@gooddosh  does this make sense ?

**Comment by gooddosh** [comment] 2023-08-27 20:21
It was intuitive and apparent to me what circles were the base and what circles correspond to the hero. What was appalling was my base moving around. It's like playing my real-life-original Competition Pro joystick without my left hand holding its base, haha. ;p THANK YOU so much for giving me a lock-down feature. I like that it's just for the joystick, so I don't have to be as accurate with my firing thumb. :D Can't wait to try it again!

**Comment by gooddosh** [comment] 2023-08-27 20:23
To answer your last question, I cannot help but move longer distances. It's my instinct. The fact that it moves at all is a big issue for me. In tense moments, I end up dragging it all over the left side of the screen. I just don't have the ability to be subtle with it, nor did I with the real joysticks. That's just me. I was always good at most of the games, but also very psychologically invested. [shrugs]

**Comment by gooddosh** [comment] 2023-08-27 20:26
If you haven't already, you might offer reverse controls for left-handed people. I'm not one of them. But I bet there's a lot of folks who might need reversed controls.

**Comment by mithrendal** [comment] 2023-08-27 20:29
I am just thinking of visualize directions ... i.e. drawing arrows for left right up down in the base ... and underly this with a click noise from a competitions pro joystick... I think that would be fun

**Comment by gooddosh** [comment] 2023-08-29 00:11
So long as click noise was optional. As much as I love the CPJ, I'd opt to have it off (by default). I did get a chance to test again. It was way better. I got much further in Jump man. Strangely, I wasn't always getting a response when my finger touched, and I died a number of times when I shouldn't have. iPhones are usually very responsive to slight touch, so might there be an issue with some touches not getting acknowledged? Still even if that weren't an issue, when I attached a joystick, my world changed. I bought a couple 8BitDo SN30 Pros. These are rather trim Nintendo-styled controllers, and they are fabulous. I still prefer CPJs, but these are so nice for travel. Shoplifter finally felt natural for me. I'm not sure touch will ever come close to the intuitive feel of a joystick. But the touch option has improved drastically with your recent upgrades!

**Comment by gooddosh** [comment] 2023-08-29 00:13
So long as click noise was optional. As much as I love the CPJ, I'd opt to have it off (by default). I did get a chance to test again. It was way better. I got much further in Jumpman. Strangely, I wasn't always getting a response when my finger touched, and I died a number of times when I shouldn't have. iPhones are usually very responsive to slight touch, so might there be an issue with some touches not getting acknowledged? Still even if that weren't an issue, when I attached a joystick (via bluetooth), my world changed. I bought a couple 8BitDo SN30 Pros. These are rather trim Nintendo-styled controllers, and they are fabulous. I still prefer CPJs, but these are so nice for travel. Choplifter finally felt natural for me. I'm not sure touch will ever come close to the intuitive feel of a joystick. But the touch option has improved drastically with your recent upgrades!

**Comment by mithrendal** [comment] 2023-08-29 05:06
>I bought a couple 8BitDo SN30 Pros

I am not sure whether they are compatible with iPhone/iPad ... you know apple only lets you connect wireless xbox, playstation or other certified MFI controllers...

You could always connect them to a chrome browser on your mac which supports all kind of controllers.. safaris on mac same as iPhone is a bit picky which controller works


>iPhones are usually very responsive to slight touch, so might there be an issue with some touches not getting acknowledged? 

we could make it more sensitive... on the other hand that might also make it more prone to an accidently and unwanted change of direction ... I will try


meanwhile I did some experiments with `drawing directions into the base` on my development machine...

<img width="894" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/d0e174ab-2d37-427e-a7d3-da8b5fee1a1b">

**Comment by gooddosh** [comment] 2023-08-29 11:36
As previously stated, I've tested 8BitDo SN30 Pros and they work.

**Comment by gooddosh** [comment] 2023-08-29 11:37
Personally, I don't think the arrows are necessary. The illustrations felt self-explanatory to me. My issue was always the moving base and the feel of the virtual mechanics.

**Comment by gooddosh** [comment] 2023-08-29 11:38
Increased sensitivity to screen touch would help, I think.

**Comment by gooddosh** [comment] 2023-08-29 11:38
The arrows diminish the aesthetic, me thinks.

**Comment by gooddosh** [comment] 2023-08-29 11:41
I want to express my awe and gratitude for all the support!

**Comment by mithrendal** [comment] 2023-09-01 09:52
>Increased sensitivity to screen touch would help, I think.

>Strangely, I wasn't always getting a response when my finger touched, and I died a number of times when I shouldn't have. 


I know now what is going on here ... 😀

The directional arrows drawn into the base helped me to understand the mechanical problem...

using the touch joystick to trigger a `right direction` joystick signal is done by dragging your finger into the right screen.  While doing this your finger leaves the base by a distance to the right e.g. 4 cm.  Then when you now want to trigger a left direction with 

`the fixed based joystick` 
your finger have to travel all the way back to the base (i.e. the 4 cm) and only then when your finger arrived a bit left to the base the `left direction` will be triggered  

`the floating base joystick`
because the base moves with your finger only a very small distance to the left will  already trigger the `left direction`


that makes the `floating joystick` compared to the fixed one much more sensitiv.


proposed Solution:
we just draw the joystick base on a fixed position but we move the `sensoric base` when the finger drags over the screen. I.e. the fixed base joystick behaves in terms of sensing the fingers like the floating base but still is only drawn on a fixed position.

@gooddosh  does that make sense ? Should I give that a try?

**Comment by gooddosh** [comment] 2023-09-01 10:02
I don't think my experience gels with this description above. The problem for me happens after I lift my left thumb and place it back down or fire (my memory of it is fading). I'll try to test it again and leave more meaningful feedback. Personally, I cannot use the floating base approach. It is completely alien to how my brain equates to a real joystick. I end up dragging it all over the screen, and it drives me insane.

**Comment by gooddosh** [comment] 2023-09-03 08:08
OK, I figured it out! :)  The problem I was having is with left-hand joystick, but it's nothing to do with how the joystick is now working (great, with the stationary base). I'm on an iPhone X still (I don't upgrade until I really start feeling the age of my tools). The "application" in horizontal view (no borders) leaves black bars on the far sides that are not usable at all; they are not part of the interface. As a result, my thumb often sets down in that region, so no joystick activates. And even if my thumb eventually is dragged into the live margin, no joystick forms. I have to touch down in the margin. I cannot touch down in the far black-bar regions. I can probably get used to this, but I wish the live-interface borders extended to the far edges of the screen. Not sure there's anything that can be done about that though, as I'm sure you've designed this UI for all sorts of screen sizes, and it is already a stellar solution.

PS: During this last test, using Choplifter, I felt like I was getting some frame lag, like the game was slowing down and frames were buffering. I tried with and without WebGL, but that didn't seem to make any difference. This is on the iPhone X of course. I haven't noticed any similar lag on my M1 MBP so far. On the phone, I also noticed on some loads of Jumpman, similar buffering. It's quite subtle in both games, so please don't imagine huge lags. These are small lags that feel like the games are choking up a bit, though they are still playable.

**Comment by mithrendal** [comment] 2023-09-03 21:08
thank you for the detailed feedback. I will look into it soon...

> I'm on an iPhone X still (I don't upgrade until I really start feeling the age of my tools).

me iPhone is even older 😅I still have got the 7Plus which does its jobs still fine... 

>The "application" in horizontal view (no borders) leaves black bars on the far sides that are not usable at all; they are not part of the interface.

well I can not try this because I am on this old iPhone... there are not yet these extra margins... do you know what is the name of these extended extra borders on the iPhone X ? We can try to google how we can extend the usable screen size of a website into these, which would probably make it then work as you expect. 

>During this last test, using Choplifter, I felt like I was getting some frame lag, like the game was slowing down and frames were buffering.

when you are on battery saving mode ... battery symbol is yellow ... then the iPhone clocks drastically down and game performance sinks ... with battery saving mode on it runs just ok on my even old iPhone 7Plus when no joystick action is drawn. When I do joystick movements it begins to stutter ...

I have reworked the virtual joystick to make it look more appealing then the current wireframe look.

<img width="894" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/2c6c9a2e-0aa5-4cc0-a44d-635788137068">

**Comment by gooddosh** [comment] 2023-09-03 22:19
Woo, that is a nice look! I thought the arrows would not be pretty, but you've achieved a VERY attractive design! That black bars probably don't have a name. I think it's just what happens when the screen dimension ratio doesn't match the newer/taller iPhones. For example, most apps (unless they are old) fill the entire screen, other than the camera island. My thumb often sets down between the island and the live area, because I'm trying to stay out of the way of the visual action.

**Comment by mithrendal** [comment] 2023-09-05 21:37
pushed the new designed `virtual joystick` into https://vc64web.github.io 😎 

also a virtual joystick frozen bug has been fixed where when your were in a touch operation and did at the same time leave the app so that it goes into background and then on bringing it in foreground again then the virtual joystick was frozen and not movable anymore ... this bug has been resolved with the new version.

with this new version also the behaviour of the fixed joystick has been altered. The base is fixed as before but the invisible sensoric  base moves now with your finger ... @gooddosh hope that it is also working fine for you.  The reason for this slight change was that with a fixed sensoric base when your finger left the screen e.g. on the left side and entered again then the middle of the base was on the border line thus it was impossible to trigger a joystick left direction again because you could hardly swipe left of the middle of the base because it was exactly on the border position.  I felt the new fixed joystick is suited better for gaming now.

**Comment by gooddosh** [comment] 2023-09-06 01:34
I don't grasp what "sensoric base moves now with your finger" means, but I'm still able to play as well as before. I feel like it's slightly more responsive than before too. I'm not feeling as much of that perceived frame lag. It's easier to fly up in Choplifter. It's getting a lot closer to a joystick experience. My last two wish-list items would be to extend the gray live margins to the very edge of the screen (black band issue) as well as a rest-area in the middle of the joystick that is non-directional — a center region of the virtual joystick where no direction is indicated. That way, we don't have to pick up our thumb to be at rest. Currently, we must pick up the thumb to be at rest, because every possible position enforces a direction. At last that is true after going in another direction first. But I already love how good this is already, and I can use it. It's just still a bit harder than an actual joystick to control. It's close though.

**Comment by mithrendal** [comment] 2023-09-06 19:03
>My last two wish-list items would be to extend the gray live margins to the very edge of the screen (black band issue)

<img width="709" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/1a0029ed-5124-42da-82a6-ee39cd7edff5">


I managed to vc64web in an XCode iPhone Simulator ... now I can try out the black band issue myself 🤓

**Comment by mithrendal** [comment] 2023-09-06 19:24
ok that was easy ... after watching some websites which have these bands and some that don't have them I found that when the website sets `viewport-fit=cover` then this makes the app to cover all the iPhone extended space ...

here in the simulator I set also borderless and cinematic widescreen to prove that all the space is used when we want to...😀

<img width="694" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/26d10671-2822-4242-b25a-239659103997">


I pushed that new baby to https://vc64web.github.io 😎

**Comment by gooddosh** [comment] 2023-09-06 20:24
Beautiful! That issue is fully resolved. I still am having frame and audio lag issue a lot of the time. I'm not in power-save mode. Not sure it's resolvable.

**Comment by mithrendal** [comment] 2023-09-07 04:36
> I still am having frame and audio lag issue a lot of the time

is warp enabled ? 

<img width="775" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/179ebc7e-3fd2-4456-9511-0bbde38bdb5a">


when warp is enabled it intentional skips frames during disk load and also audio is distorted.

**Comment by gooddosh** [comment] 2023-09-07 05:51
Yes, but that wasn't it. I wouldn't even use the software if it didn't have Warp. That's one thing I don't miss about the real C64. AND, I love that you implemented it automatically just for disk load times. One cool addition would be Warp during disk activity and 2x during regular activity. I'd probably switch to this software full time instead of VICE when playing RPGs, if I could do this. I am still trying to finish Pool of Radiance from when I was a teenager. I play that at 2x speed and manually enable WARP during load times using a key command.

I did figure it out the frame and audio lags though. It's SID Interpolation mode. Once I set it back to SID Fast, the issue completely vanished!

**Comment by mithrendal** [comment] 2023-09-07 21:07
>My only remaining wish is that the center of the virtual joystick had a wider non-directional rest state, and that I need to move out of the center "safe" area to invoke a direction.

I played with the safe area or rest zone ... I am unsure about how wide it should be... when I make it too large 🫣 then the joystick becomes unresponsive slow and laggy while playing river raid ... when the rest zone is 0 like before than it is maybe too sensitive ... I now pushed a version with 20 pixels wideness of that safe area zone ...

🤔 probably we should add a setting for this... sensitivity or virtual joystick dead zone size ...

**Comment by gooddosh** [comment] 2023-09-08 02:27
I like the idea of being able customize the radius of that setting. Just a guess, but I'll probably feel similar about what feels natural. I'll test soon and update. This virtual controller is really starting to feel competitive!

**Comment by gooddosh** [comment] 2023-09-08 04:09
It's almost there. I agree. I think the rest zone could be a tiny bit smaller actually, perhaps 16 or 12 as a default with the option to customize it. I love this progress. This product is a dream come true, and I feel like a lucid dreamer. LOL. Nice work all around!

**Comment by gooddosh** [comment] 2023-09-08 04:35
Even 10 might be OK. Guess I'd have to try, but I bet 12 is a good starting point.

**Comment by mithrendal** [comment] 2023-09-08 20:08
>This product is a dream come true

🫡

lets implement the following settings 
`
virtual joystick = ` `base moves`, `base fixed on first touch`, `stationary` 
`dead zone` = 0,8,12,16,24 (defaults to 12)

`virtual joystick =` `stationary` type is fixed always in the lower left corner and always visible. This one allows to just touch the always visible direction panel segments to trigger a certain direction. Will be suited better for games where you have to click a certain direction like the mini game paradroid for example.

**Comment by gooddosh** [comment] 2023-09-08 21:29
12 might be a bit tight. Gonna try 14.

Getting occasional freezes of fire button position. When it occurs, fire doesn't function. Happens a lot when a call is received, or I leave the app and return to it. During this last test, it happened without leaving the app. Lost a life started next life (Choplifter), and the fire-button circle was frozen onscreen.

**Comment by gooddosh** [comment] 2023-09-08 21:30
Moving out of the app and returning made the fire freeze issue go away (work-around).

**Comment by gooddosh** [comment] 2023-09-08 21:32
Couldn't find options to alter dead zone to 14 or test stationary joystick.

**Comment by gooddosh** [comment] 2023-09-08 21:34
PS: Once this is all ironed out, I plan to evangelize vc64web in all the groups I'm involved with. Really looking forward to more people becoming aware of it. I'm not that well connected, but I'm in a couple Facebook groups and belong to the Patreon group of a well known YouTube channel. I'll do what I can to promote it!

**Comment by gooddosh** [comment] 2023-09-08 22:16
Side note: I think SID quality options should come with a warning such as: Changing SID settings from Fast may impact performance on less powerful systems, such as phones.

**Comment by mithrendal** [comment] 2023-09-09 09:00
>Couldn't find options to alter dead zone to 14 nor test stationary joystick.

😂 it is only in my mind yet… I was only thinking and planning to do it the next couple of days…

I will also look after the occasionally fire freezes

> I plan to evangelize vc64web in all the groups I'm involved with

cool 😎 and thank you for your support

this issue will be continued in part 2

**Closed by mithrendal** 2023-09-09 09:00 UTC
Labels: bug

**Comment by mithrendal** [comment] 2023-09-09 11:42
> Side note: I think SID quality options should come with a warning such as: Changing SID settings from Fast may impact performance on less powerful systems, such as phones. I was fortunate to guess that as a root cause of frame and audio lag so quickly. Lucky guess.

Yes lucky 😀. we can measure/watch the impact of better resid quality on the mac when comparing the processor utilization in the macOS activity monitor.
